-- Generated by tools/build_products.py. Do not edit by hand.
local _, ns = ...

ns.Data.instances.blackfathom_deeps.verificationStatus = "vanillaBaseline"
ns.Data.instances.blackrock_depths.verificationStatus = "vanillaBaseline"
ns.Data.instances.dire_maul.verificationStatus = "vanillaBaseline"
ns.Data.instances.gnomeregan.verificationStatus = "vanillaBaseline"
ns.Data.instances.lower_blackrock_spire.verificationStatus = "vanillaBaseline"
ns.Data.instances.maraudon.verificationStatus = "vanillaBaseline"
ns.Data.instances.ragefire_chasm.verificationStatus = "vanillaBaseline"
ns.Data.instances.razorfen_downs.verificationStatus = "vanillaBaseline"
ns.Data.instances.razorfen_kraul.verificationStatus = "vanillaBaseline"
ns.Data.instances.scarlet_monastery.verificationStatus = "vanillaBaseline"
ns.Data.instances.scholomance.verificationStatus = "vanillaBaseline"
ns.Data.instances.shadowfang_keep.verificationStatus = "vanillaBaseline"
ns.Data.instances.stratholme.verificationStatus = "vanillaBaseline"
ns.Data.instances.sunken_temple.verificationStatus = "vanillaBaseline"
ns.Data.instances.the_deadmines.verificationStatus = "vanillaBaseline"
ns.Data.instances.the_stockade.verificationStatus = "vanillaBaseline"
ns.Data.instances.uldaman.verificationStatus = "vanillaBaseline"
ns.Data.instances.upper_blackrock_spire.verificationStatus = "vanillaBaseline"
ns.Data.instances.wailing_caverns.verificationStatus = "vanillaBaseline"
ns.Data.instances.zulfarrak.verificationStatus = "vanillaBaseline"

ns.Data.instances.hall_of_thanes = {
    key = "hall_of_thanes",
    name = "The Hall of Thanes",
    contentType = "dungeon",
    clientFlavors = { forever = true },
    levelMin = 13,
    levelMax = 18,
    verificationStatus = "announced",
    bosses = {},
}
ns.Data.loot.hall_of_thanes = {}

ns.Data.instances.ruins_of_lordaeron = {
    key = "ruins_of_lordaeron",
    name = "Ruins of Lordaeron",
    contentType = "dungeon",
    clientFlavors = { forever = true },
    levelMin = 15,
    levelMax = 20,
    verificationStatus = "announced",
    bosses = {},
}
ns.Data.loot.ruins_of_lordaeron = {}

ns.Data.instances.excavation_site_wetlands = {
    key = "excavation_site_wetlands",
    name = "Excavation Site: Wetlands",
    contentType = "dungeon",
    clientFlavors = { forever = true },
    levelMin = 24,
    levelMax = 29,
    verificationStatus = "announced",
    bosses = {},
}
ns.Data.loot.excavation_site_wetlands = {}

ns.Data.instances.city_of_dalaran = {
    key = "city_of_dalaran",
    name = "City of Dalaran",
    contentType = "dungeon",
    clientFlavors = { forever = true },
    levelMin = 28,
    levelMax = 33,
    verificationStatus = "announced",
    bosses = {},
}
ns.Data.loot.city_of_dalaran = {}

ns.Data.instances.the_drowned_city = {
    key = "the_drowned_city",
    name = "The Drowned City",
    contentType = "dungeon",
    clientFlavors = { forever = true },
    levelMin = 35,
    levelMax = 40,
    verificationStatus = "announced",
    bosses = {},
}
ns.Data.loot.the_drowned_city = {}

ns.Data.instances.kroldok_stronghold = {
    key = "kroldok_stronghold",
    name = "Krol'dok Stronghold",
    contentType = "dungeon",
    clientFlavors = { forever = true },
    levelMin = 40,
    levelMax = 45,
    verificationStatus = "announced",
    bosses = {},
}
ns.Data.loot.kroldok_stronghold = {}

ns.Data.instances.alcaz_prison = {
    key = "alcaz_prison",
    name = "Alcaz Prison",
    contentType = "dungeon",
    clientFlavors = { forever = true },
    levelMin = 48,
    levelMax = 53,
    verificationStatus = "announced",
    bosses = {},
}
ns.Data.loot.alcaz_prison = {}

ns.Data.instances.blackmaw_hold = {
    key = "blackmaw_hold",
    name = "Blackmaw Hold",
    contentType = "dungeon",
    clientFlavors = { forever = true },
    levelMin = 55,
    levelMax = 60,
    verificationStatus = "announced",
    bosses = {},
}
ns.Data.loot.blackmaw_hold = {}

ns.Data.instances.shapers_terrace = {
    key = "shapers_terrace",
    name = "Shaper's Terrace",
    contentType = "dungeon",
    clientFlavors = { forever = true },
    levelMin = 58,
    levelMax = 60,
    verificationStatus = "announced",
    bosses = {},
}
ns.Data.loot.shapers_terrace = {}
